# Generated by Django 6.0.3 on 2026-05-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakra',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='fakra',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fakra',
            name='status',
        ),
        migrations.DeleteModel(
            name='FakraAccess',
        ),
    ]
