# Generated by Django 6.0.4 on 2026-06-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakras', '0003_fakra_description_fakra_due_date_fakra_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakra',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
