# Generated by Django 6.0.4 on 2026-06-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakras', '0006_itemattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
