# Generated by Django 6.0.4 on 2026-06-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakras', '0007_item_estimated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakra',
            name='budget_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
