# Generated by Django 6.0.4 on 2026-07-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakras', '0008_fakra_budget_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakra',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
