# Generated by Django 6.0.3 on 2026-04-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_remove_item_fakra_remove_item_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(default='member', max_length=10),
        ),
    ]
