# Generated by Django 6.0.3 on 2026-05-05 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_alter_membership_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='household',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'household')},
        ),
        migrations.AddField(
            model_name='household',
            name='invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'household'], name='household_m_user_id_ff4320_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('household',), name='one_owner_per_household'),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='joined_at',
        ),
    ]
