# Generated by Django 6.0.3 on 2026-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0005_remove_household_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='one_owner_per_household',
        ),
        migrations.AlterField(
            model_name='household',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
