# Generated by Django 6.0.4 on 2026-07-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0007_household_created_at_membership_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='type',
            field=models.CharField(choices=[('family', 'Family'), ('community', 'Community'), ('organization', 'Organization'), ('society', 'Society'), ('other', 'Other')], default='family', max_length=20),
        ),
    ]
